---
title: "Cahier de laboratoire"
author: "Marika Roberge, Juliette Boulet-Thomas et Bertrand Labrecque"

output: html_document
---
Travail de session sur les lépidoptères
====================================

## Nos questions de recherche
Avoir une question large et 3 questions plus spécifiques

**Question principale** :  
Quels sont les changements de la composition et l’abondance des espèces de lépidoptères dans le temps et dans l’espace ?

### **Variation temporelle**  
Comment la composition des communautés de lépidoptères a-t-elle évolué au fil des années dans un site donné ?

### **Variation spatiale**  
Comment la composition et l’abondance des communautés de lépidoptères varient-elles selon les différentes localisations géographiques ?


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
À faire : 
1. changer les noms de colonnes de la table de données brutes pour que ca soit plus compréhensible
2. ajouter des étapes dans la fonction nettoyage_data : pour enlever TXX:XX:XX de dwc_event_date et ajuster ca dans verification_data
3. S'assurer que obs_value réfère à quelque chose en particulier (presence, abondance, et ajuster les données de ca, ex. 11 111)
4. Dans la table secondaire date, voir à ce que chaque ligne soit unique (ex. site de 1 à 10 (donc de 10 lignes de combinaison de lat et lon unique) et dans table primaire à site_id on retrouverait chaque ligne avec 1 à 10)
5. Dans la table primaire on aurait les colonnes : nom_scientifique (observed_scientific_name), date (dwc_event_date), abondance (obs_value en filtrant seulement pour abundance dans obs_variable) et site_id et ?
6. Changer le nom de certains targets (ex. data_final et ULTIME_database)

Updates: 
2. réglé dans la fonction type_colone, rete en characters
3. problème de 11111 réglé

À faire cette semaine (jusqu'à mardi soir 8 avril) :
-Corriger l'étape 2 de ''À faire''
-Revoir le 11 111, qu'est ce qu'on fait avec et qu'est-ce qu'on fait avec l'abondance dans nos analyses?
-Clairer le site_id (faire le df pour le site_id)
-Injecter les données
-S'assurer que SQL et targets fonctionnent (et que le MarkDown aussi)
-Ajouter une ligne de retrait de base de données lepido dans le script de SQL
-Identifier clairement nos questions de recherches 
-Penser à ce qu'on veut présenter comme figures
-Commencer à écrire le texte dans le cahier de laboratoire
